# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/igrr/astyle_py.git
    rev: v1.0.5
    hooks:
      - id: astyle_py
        args: ['--rules=tools/ci/astyle_config.yaml']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        types_or: [c, c++]
      - id: end-of-file-fixer
        types_or: [c, c++]
